backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should be changed to the correct repo in your GitHub account
repo: "exgael/ari-dictionary"

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

collections:
  - name: "noun" # Used in routes, e.g., /admin/collections/noun
    label: "Noun" # Used in the UI
    folder: "content/nouns" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Term", name: "term", widget: "string" }
      - { label: "Language", name: "language", widget: "select", options: ["DARIJA", "ENGLISH", "FRENCH"] }
      - { label: "Gender", name: "gender", widget: "select", options: ["MASCULINE", "FEMININE", "NEUTER"] }
      - { label: "Number", name: "number", widget: "select", options: ["SINGULAR", "PLURAL"] } 