backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should be changed to the correct repo in your GitHub account
repo: "FreeMusketeer/ari-dictionary"




# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: FreeMusketeer/ari-dictionary
  branch: main
  identity_url: https://auth.decapbridge.com/sites/ad2b25a8-a077-4417-bca3-1393f1059287
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://whimsical-malasada-88307d.netlify.app

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

collections:
  - name: "noun" # Used in routes, e.g., /admin/collections/noun
    label: "Noun" # Used in the UI
    folder: "content/nouns" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Term", name: "term", widget: "string" }
      - { label: "Language", name: "language", widget: "select", options: ["DARIJA", "ENGLISH", "FRENCH"] }
      - { label: "Gender", name: "gender", widget: "select", options: ["MASCULINE", "FEMININE", "NEUTER"] }
      - { label: "Number", name: "number", widget: "select", options: ["SINGULAR", "PLURAL"] } 