backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Update this to your repository
repo: "benoitbarbier/DarijaDictionary" # e.g., "user/repo"

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

collections:
  - name: "lexical_entries"
    label: "Lexical Entries"
    label_singular: "Lexical Entry"
    folder: "_data/lexical_entries"
    create: true
    slug: "{{term}}-{{id}}"
    summary: "{{term}} ({{part_of_speech}} - {{language}})"
    fields:
      # --- Common Fields ---
      - { label: "ID", name: "id", widget: "ncw-id", prefix: "entry", hidden: true }
      - { label: "Term", name: "term", widget: "string" }
      - { label: "Language", name: "language", widget: "select", options: ["DARIJA", "ENGLISH", "FRENCH"] }
      - { label: "Part of Speech", name: "part_of_speech", widget: "select", options: ["NOUN", "ADJECTIVE", "VERB", "PRONOUN", "ADVERB", "PREPOSITION", "CONJUNCTION"] }
      - { label: "Notes", name: "notes", widget: "text", required: false }

      # --- Noun Details ---
      - label: "Noun Details"
        name: "noun_details"
        widget: "object"
        required: false
        condition: { field: "part_of_speech", value: "NOUN" }
        fields:
          - { label: "Gender", name: "gender", widget: "select", options: ["MASCULINE", "FEMININE", "NEUTER"] }
          - { label: "Number", name: "number", widget: "select", options: ["SINGULAR", "PLURAL"] }

      # --- Adjective Details ---
      - label: "Adjective Details"
        name: "adjective_details"
        widget: "object"
        required: false
        condition: { field: "part_of_speech", value: "ADJECTIVE" }
        fields:
          - { label: "Adjective Type", name: "adjective_type", widget: "select", options: ["DESCRIPTIVE", "DEMONSTRATIVE", "POSSESSIVE", "INTERROGATIVE", "INDEFINITE", "PROPER", "QUANTITATIVE", "DISTRIBUTIVE", "COMPARATIVE", "SUPERLATIVE"] }
          - { label: "Gender", name: "gender", widget: "select", options: ["MASCULINE", "FEMININE", "NEUTER"], required: false }
          - { label: "Number", name: "number", widget: "select", options: ["SINGULAR", "PLURAL"], required: false }

      # --- Verb Details ---
      - label: "Verb Details"
        name: "verb_details"
        widget: "object"
        required: false
        condition: { field: "part_of_speech", value: "VERB" }
        fields:
          - { label: "Verb Type", name: "verb_type", widget: "select", options: ["STATIVE", "ACTION", "MODAL", "AUXILIARY"], required: false }
          - { label: "Regularity", name: "regularity", widget: "select", options: ["REGULAR", "IRREGULAR"] }
          - { label: "Transitivity", name: "transitivity", widget: "select", options: ["TRANSITIVE", "INTRANSITIVE", "DITRANSITIVE"], required: false }
          - { label: "Conjugation Rule", name: "conjugation_rule", widget: "select", options: ["BASE", "CCV_REPLACE", "CVC_REPLACE", "KLAA", "KHDAA"], required: false, hint: "For Darija verbs only" }

      # --- Pronoun Details ---
      - label: "Pronoun Details"
        name: "pronoun_details"
        widget: "object"
        required: false
        condition: { field: "part_of_speech", value: "PRONOUN" }
        fields:
          - { label: "Pronoun Type", name: "pronoun_type", widget: "select", options: ["PERSONAL", "POSSESSIVE", "DEMONSTRATIVE", "INTERROGATIVE", "RELATIVE", "INDEFINITE"] }
          - { label: "Person", name: "person", widget: "select", options: ["FIRST", "SECOND", "THIRD"] }
          - { label: "Gender", name: "gender", widget: "select", options: ["MASCULINE", "FEMININE", "NEUTER"] }
          - { label: "Number", name: "number", widget: "select", options: ["SINGULAR", "PLURAL"] }

      # --- Adverb Details ---
      - label: "Adverb Details"
        name: "adverb_details"
        widget: "object"
        required: false
        condition: { field: "part_of_speech", value: "ADVERB" }
        fields:
          - { label: "Adverb Type", name: "adverb_type", widget: "select", options: ["MANNER", "PLACE", "TIME", "FREQUENCY", "DEGREE", "CAUSE"] }

      # --- Preposition Details ---
      - label: "Preposition Details"
        name: "preposition_details"
        widget: "object"
        required: false
        condition: { field: "part_of_speech", value: "PREPOSITION" }
        fields:
          - { label: "Preposition Type", name: "preposition_type", widget: "select", options: ["TEMPORAL", "LOCATIVE", "MANNER_INSTRUMENT", "CAUSE_PURPOSE"] }

      # --- Conjunction Details ---
      - label: "Conjunction Details"
        name: "conjunction_details"
        widget: "object"
        required: false
        condition: { field: "part_of_speech", value: "CONJUNCTION" }
        fields:
          - { label: "Conjunction Type", name: "conjunction_type", widget: "select", options: ["COORDINATING", "SUBORDINATING", "CORRELATIVE_PAIR_OF"] }

      # --- Relationships ---
      - label: "Relationships"
        name: "relationships"
        widget: "list"
        required: false
        fields:
          - { label: "Type", name: "type", widget: "select", options: ["TRANSLATION_OF", "PLURAL_OF", "SYNONYM_OF", "ANTONYM_OF", "SEE_ALSO", "COMPARATIVE_OF", "SUPERLATIVE_OF"] }
          - { label: "Target", name: "target", widget: "relation", collection: "lexical_entries", search_fields: ["term"], value_field: "id", display_fields: ["term", "part_of_speech", "language"] }

      